// src/styles.js
// Shared inline style tokens. Import into any component.

export const tokens = {
  bg:        "#0d0d0f",
  surface:   "#141417",
  border:    "#252529",
  border2:   "#333338",
  text:      "#eae8e3",
  muted:     "#6e6c75",
  accent:    "#e8c547",
  mono:      "'Syne Mono', monospace",
  head:      "'Syne', sans-serif",
  body:      "'Lora', Georgia, serif",
};

export const s = {
  page: {
    background:    tokens.bg,
    color:         tokens.text,
    fontFamily:    tokens.body,
    minHeight:     "100vh",
    display:       "flex",
    flexDirection: "column",
    alignItems:    "center",
    padding:       "0 16px 80px",
  },
  card: {
    border:       `1px solid ${tokens.border}`,
    borderRadius: 6,
    overflow:     "hidden",
    marginBottom: 12,
  },
  cardHead: {
    display:        "flex",
    alignItems:     "center",
    gap:            12,
    padding:        "11px 18px",
    background:     tokens.surface,
    borderBottom:   `1px solid ${tokens.border}`,
  },
  cardBody: {
    padding:    18,
    background: tokens.bg,
  },
  stepNum: {
    fontFamily:    tokens.mono,
    fontSize:      9,
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    color:         tokens.muted,
  },
  stepName: {
    fontFamily:    tokens.head,
    fontSize:      11,
    fontWeight:    700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color:         tokens.text,
  },
  textarea: {
    width:      "100%",
    minHeight:  140,
    background: tokens.surface,
    border:     `1px solid ${tokens.border}`,
    borderRadius: 4,
    padding:    "14px 16px",
    fontFamily: tokens.body,
    fontSize:   15,
    lineHeight: 1.7,
    color:      tokens.text,
    resize:     "vertical",
    outline:    "none",
    boxSizing:  "border-box",
  },
  charCount: {
    fontFamily:    tokens.mono,
    fontSize:      10,
    color:         tokens.muted,
    textAlign:     "right",
    marginTop:     6,
  },
  rewriteBtn: (isLoading) => ({
    width:         "100%",
    background:    isLoading ? "#3a3a42" : tokens.text,
    color:         isLoading ? tokens.muted : tokens.bg,
    border:        "none",
    borderRadius:  6,
    padding:       17,
    fontFamily:    tokens.head,
    fontSize:      13,
    fontWeight:    800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    cursor:        isLoading ? "not-allowed" : "pointer",
    marginBottom:  12,
  }),
  error: {
    padding:      "12px 16px",
    background:   "#1f0e0c",
    border:       "1px solid #5c2820",
    borderRadius: 4,
    fontFamily:   tokens.mono,
    fontSize:     11,
    color:        "#e05c4b",
    marginBottom: 12,
  },
};